version: "3"

services:
  server:
    image: node:13-alpine
    container_name: brender_cn_server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: sh -c "npm config set registry https://registry.npm.taobao.org && npm install && npm run dev"
