version: "3"

services:
  server:
    image: node_dev
    container_name: brender_cn_server
    working_dir: /usr/app
    volumes:
      - ./src:/usr/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
      # - "3000:3000"
    expose:
      - "5671"
    # command: sh -c "npm config set registry https://registry.npm.taobao.org && npm install && npm run dev"
